In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Carga do conjunto de dados
# trocar o meu caminho onde salvei este arquivo pelo de vocês
#
precos_casas = pd.read_csv("C:/Users/enggi/IA_CURSO/Análise De Dados E Engenharia De Características/Aula02/Tamanho_pinguins.csv")
dados_pinguins = pd.read_csv("C:/Users/enggi/IA_CURSO/Análise De Dados E Engenharia De Características/Aula02/PrecosCasas.csv")
#
# para maiores informações sobre os conjuntos de dados usados neste lab acessar:
# https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis
# https://www.kaggle.com/datasets/parulpandey/palmer-archipelago-antarctica-penguin-data

In [5]:
dados_pinguins = pd.read_csv("C:/Users/enggi/IA_CURSO/Análise De Dados E Engenharia De Características/Aula02/Tamanho_pinguins.csv")
precos_casas = pd.read_csv("C:/Users/enggi/IA_CURSO/Análise De Dados E Engenharia De Características/Aula02/PrecosCasas.csv")

In [6]:
dados_pinguins = dados_pinguins[['species','culmen_length_mm']]

In [7]:
dados_pinguins.head()

  species  culmen_length_mm
0  Adelie              39.1
1  Adelie              39.5
2  Adelie              40.3
3  Adelie               NaN
4  Adelie              36.7

In [8]:
print("\nBase filtrada:")
display(dados_pinguins.head())

Base filtrada:

  species  culmen_length_mm
0  Adelie              39.1
1  Adelie              39.5
2  Adelie              40.3
3  Adelie               NaN
4  Adelie              36.7

In [9]:
dados_pinguins.shape

(344, 2)

In [10]:
print("Número de linhas:", dados_pinguins.shape[0])
print("Número de colunas:", dados_pinguins.shape[1])

Número de linhas: 344
Número de colunas: 2